### ISSUE TITLE
Connect to LDAPS server without certificate verification

### ISSUE THREAD

**Issue by fjcloud** [pinepain/ldap-auth-proxy#17]
Hello, all is in the title ...! Does a env variable exist for that ?

**Comment by pinepain** [comment]
Hi, I guess what you asked could be achieved with `InsecureSkipVerify=true` `LDAP_SERVER` parameter, here's a test that demonstrates this capability - https://github.com/pinepain/ldap-auth-proxy/blob/master/ldap_test.go#L70, though, I personally have never used this feature with this ldap auth proxy.

**Comment by fjcloud** [comment]
Thank you for your help!

I tried LDAP_SERVER_InsecureSkipVerify=true and
LDAP_SERVER_INSECURESKIPVERIFY=true

but it still drop an error when the container want to connect to the ldaps server. Do you think a workaround exist ?

**Comment by pinepain** [comment]
Give `LDAP_SERVER=ldaps://example.com?InsecureSkipVerify=true` a try where `example.com` replaced with actual LDAP server name/address.

**Comment by fjcloud** [comment]
Oh it work ! i tried ```LDAP_SERVER=ldaps://example.com&InsecureSkipVerify=true```, i wasn't that far ahah. Thank you very much!
